[project]
name = "depi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Manwelws", email = "manwelwasfystu@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "pygments>=2.21.0",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
]

[project.scripts]
depi = "depi:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "Depi/data-analysis/Project/Team",
    "data-analysis/Project/Team",
]
